apiVersion: v2
name: gotify
description: a simple server for sending and receiving messages
type: application
version: 0.1.0
appVersion: "2.2.0"
dependencies:
  - name: common
    version: 0.1.10
    repository: file://../common
