configMaps: {}

secrets: {}

type: deployment

annotations: {}

labels: {}

replicas: 1

affinity: {}

args: []

command: []

env: {}

envFrom: []

image:
  repository:
  tag:
  pullPolicy:

livenessProbe: {}

services: {}

readinessProbe: {}

resources: {}

securityContext: {}

persistence: {}

extraContainers: {}

dnsConfig: {}

dnsPolicy:

hostNetwork: false

initContainers: {}

nodeName:

nodeSelector: {}

runtimeClassName: 

podSecurityContext: {}

serviceAccountName: 

tolerations: {}

extraWorkloads: []

extraObjects: []

extraObjects2: []

sidecars:
  codeserver:
    enabled: false

    image:
      repository: linuxserver/code-server
      tag: amd64-4.9.1

    persistence: {}

    services:
      http:
        port: 8443

  vpn:
    enabled: false

    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - SYS_MODULE

    image:
      repository: dperson/openvpn-client
      tag: latest

    # env:
    #   ROUTE: "10.0.0.0/8"
    #   FIREWALL: "on"

    # dnsConfig:
    #   options:
    #     - name: ndots
    #       value: "1"

    # livenessProbe:
    #   exec:
    #     command:
    #       - sh 
    #       - -c
    #       - if [ $(curl -s https://ifconfig.co/country-iso) == 'US']; then exit 0; else exit $?; fi
    #   initialDelaySeconds: 30
    #   periodSeconds: 60 
    #   failureThreshold: 1

    # readinessProbe:
    #   exec:
    #     command:
    #       - sh 
    #       - -c
    #       - if [ $(curl -s https://ifconfig.co/country-iso) == 'US']; then exit 0; else exit $?; fi
    #   initialDelaySeconds: 30
    #   periodSeconds: 60 
    #   failureThreshold: 1

    auth: |

    configFile: |
