env:
  TZ: America/Los_Angeles

ingress:
  enabled: true
  hosts:
  - name: default
    host: calibre.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 32Gi

  import:
    enabled: true
    type: nfs
    server: 192.168.55.20
    path: /mnt/user/backup/ebooks
