repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: nvidia
    url: https://helm.ngc.nvidia.com/nvidia
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/
  - name: homelab
    url: https://jasonb5.github.io/charts

templates:
  production:
    namespace: production
    missingFileHandler: Warn
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml

releases:
- name: jellyfin
  chart: homelab/jellyfin
  version: 0.1.0
  inherit:
  - template: production
- name: jupyterhub
  chart: jupyterhub/jupyterhub
  version: 3.1.0
  inherit:
  - template: production
- name: gpu-operator
  namespace: gpu-operator
  chart: nvidia/gpu-operator
  version: v23.6.1
  inherit:
  - template: production
  disableValidationOnInstall: true
  dependencies:
  - chart: homelab/common-test
    version: 0.1.0
  hooks:
  - events: ["postsync"]
    command: "kubectl"
    args: ["-n", "gpu-operator", "patch", "clusterpolicy/cluster-policy", "--type", "merge", "--patch-file", "patches/gpu-operator.yaml"]
- name: traefik
  chart: traefik/traefik
  version: 24.0.0
  inherit:
  - template: production
  disableValidationOnInstall: true
  dependencies:
  - chart: homelab/common-test
    version: 0.1.0
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  version: 1.5.1
  inherit:
  - template: production
  dependencies:
  - chart: homelab/common-test
    version: 0.1.0
