repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: nvidia
    url: https://helm.ngc.nvidia.com/nvidia
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/
  - name: homelab
    url: https://jasonb5.github.io/charts

templates:
  production:
    namespace: production
    missingFileHandler: Warn
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml
  presync:
    hooks:
    - events:
      - presync
      command: /bin/bash
      args:
      - -c
      - "config/{{`{{ .Release.Name }}`}}/presync.sh install {{`{{ .Release.Namespace }}`}}"
      showlogs: true
    - events:
      - preuninstall
      command: /bin/bash
      args:
      - -c
      - "config/{{`{{ .Release.Name }}`}}/presync.sh preuninstall {{`{{ .Release.Namespace }}`}}"
      showlogs: true
    - events:
      - postuninstall
      command: /bin/bash
      args:
      - -c
      - "config/{{`{{ .Release.Name }}`}}/presync.sh postuninstall {{`{{ .Release.Namespace }}`}}"
      showlogs: true
  postsync:
    hooks:
    - events:
      - postsync
      command: /bin/bash
      args:
      - -c
      - "config/{{`{{ .Release.Name }}`}}/postsync.sh install {{`{{ .Release.Namespace }}`}}"
      showlogs: true
    - events:
      - preuninstall
      command: /bin/bash
      args:
      - -c
      - "config/{{`{{ .Release.Name }}`}}/postsync.sh preuninstall {{`{{ .Release.Namespace }}`}}"
      showlogs: true
    - events:
      - postuninstall
      command: /bin/bash
      args:
      - -c
      - "config/{{`{{ .Release.Name }}`}}/postsync.sh postuninstall {{`{{ .Release.Namespace }}`}}"
      showlogs: true

releases:
- name: zwave-js-ui
  chart: homelab/zwave-js-ui
  version: 0.1.0
  inherit:
  - template: production
- name: node-red
  chart: homelab/node-red
  version: 0.1.0
  inherit:
  - template: production
- name: photoprism
  chart: homelab/photoprism
  version: 0.1.0
  inherit:
  - template: production
- name: homeassistant
  chart: homelab/homeassistant
  version: 0.1.0
  inherit:
  - template: production
  - template: postsync
- name: mealie
  chart: homelab/mealie
  version: 0.1.0
  inherit:
  - template: production
- name: gotify
  chart: homelab/gotify
  version: 0.1.1
  inherit:
  - template: production
- name: jellyfin
  chart: homelab/jellyfin
  version: 0.1.0
  inherit:
  - template: production
- name: jupyterhub
  installed: false
  chart: jupyterhub/jupyterhub
  version: 3.1.0
  inherit:
  - template: production
- name: gpu-operator
  installed: false
  namespace: gpu-operator
  chart: nvidia/gpu-operator
  version: v23.6.1
  inherit:
  - template: production
  - template: postsync
  disableValidationOnInstall: true
  dependencies:
  - chart: homelab/common-test
    version: 0.1.0
- name: traefik
  chart: traefik/traefik
  version: 26.0.0
  inherit:
  - template: production
  disableValidationOnInstall: true
  dependencies:
  - chart: homelab/commonlib
    version: 0.1.0
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  version: 1.5.3
  inherit:
  - template: production
  dependencies:
  - chart: homelab/commonlib
    version: 0.1.0
