releases:
- chart: homelab/calibre-web
  inherit:
  - template: production
  name: calibre-web
  version: 0.1.4
- chart: homelab/anythingllm
  inherit:
  - template: production
  name: anythingllm
  version: 0.1.2
- chart: grafana/loki-stack
  inherit:
  - template: monitoring
  installed: false
  name: loki
  version: 2.10.2
- chart: prometheus-community/prometheus
  inherit:
  - template: monitoring
  installed: false
  name: prometheus
  version: 25.22.0
- chart: homelab/it-tools
  inherit:
  - template: production
  name: it-tools
  version: 0.1.5
- chart: homelab/homebox
  inherit:
  - template: production
  - template: backup
  name: homebox
  version: 0.1.4
- chart: homelab/zwave-js-ui
  inherit:
  - template: production
  - template: backup
  name: zwave-js-ui
  version: 0.1.21
- chart: homelab/node-red
  inherit:
  - template: production
  - template: backup
  name: node-red
  version: 0.1.13
- chart: homelab/photoprism
  inherit:
  - template: production
  - template: backup
  name: photoprism
  version: 0.1.8
- chart: homelab/homeassistant
  inherit:
  - template: production
  - template: backup
  name: homeassistant
  version: 0.1.34
- chart: homelab/mealie
  inherit:
  - template: production
  - template: backup
  name: mealie
  version: 0.1.6
- chart: homelab/gotify
  inherit:
  - template: production
  - template: backup
  name: gotify
  version: 0.1.6
- chart: homelab/jellyfin
  inherit:
  - template: production
  - template: backup
  name: jellyfin
  version: 0.1.9
- chart: jupyterhub/jupyterhub
  inherit:
  - template: production
  installed: false
  name: jupyterhub
  version: 3.3.7
- chart: nvidia/gpu-operator
  dependencies:
  - chart: homelab/common-test
    version: 0.1.0
  disableValidationOnInstall: true
  inherit:
  - template: production
  - template: postsync
  installed: false
  name: gpu-operator
  namespace: gpu-operator
  version: v24.3.0
- chart: traefik/traefik
  dependencies:
  - chart: homelab/commonlib
    version: 0.1.0
  disableValidationOnInstall: true
  inherit:
  - template: production
  name: traefik
  version: 28.3.0
- chart: longhorn/longhorn
  dependencies:
  - chart: homelab/commonlib
    version: 0.1.0
  inherit:
  - template: production
  name: longhorn
  namespace: longhorn-system
  version: 1.6.2
repositories:
- name: longhorn
  url: https://charts.longhorn.io
- name: traefik
  url: https://traefik.github.io/charts
- name: nvidia
  url: https://helm.ngc.nvidia.com/nvidia
- name: jupyterhub
  url: https://jupyterhub.github.io/helm-chart/
- name: homelab
  url: https://jasonb5.github.io/charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
templates:
  backup:
    values:
    - config/rclone/values.yaml
  monitoring:
    missingFileHandler: Warn
    namespace: monitoring
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml
  postsync:
    hooks:
    - args:
      - -c
      - config/{{`{{ .Release.Name }}`}}/postsync.sh install {{`{{ .Release.Namespace
        }}`}}
      command: /bin/bash
      events:
      - postsync
      showlogs: true
    - args:
      - -c
      - config/{{`{{ .Release.Name }}`}}/postsync.sh preuninstall {{`{{ .Release.Namespace
        }}`}}
      command: /bin/bash
      events:
      - preuninstall
      showlogs: true
    - args:
      - -c
      - config/{{`{{ .Release.Name }}`}}/postsync.sh postuninstall {{`{{ .Release.Namespace
        }}`}}
      command: /bin/bash
      events:
      - postuninstall
      showlogs: true
  presync:
    hooks:
    - args:
      - -c
      - config/{{`{{ .Release.Name }}`}}/presync.sh install {{`{{ .Release.Namespace
        }}`}}
      command: /bin/bash
      events:
      - presync
      showlogs: true
    - args:
      - -c
      - config/{{`{{ .Release.Name }}`}}/presync.sh preuninstall {{`{{ .Release.Namespace
        }}`}}
      command: /bin/bash
      events:
      - preuninstall
      showlogs: true
    - args:
      - -c
      - config/{{`{{ .Release.Name }}`}}/presync.sh postuninstall {{`{{ .Release.Namespace
        }}`}}
      command: /bin/bash
      events:
      - postuninstall
      showlogs: true
  production:
    missingFileHandler: Warn
    namespace: production
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml
