repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: nvidia
    url: https://helm.ngc.nvidia.com/nvidia
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/

templates:
  production:
    namespace: production
    missingFileHandler: Warn
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml

releases:
- name: jupyterhub
  chart: jupyterhub/jupyterhub
  version: 2.0.0
  inherit:
  - template: production
- name: jellyfin
  chart: ../charts/charts/jellyfin
  version: 0.1.0
  inherit:
  - template: production
- name: gpu-operator
  namespace: gpu-operator
  chart: nvidia/gpu-operator
  version: v23.3.2
  inherit:
  - template: production
  disableValidationOnInstall: true
  dependencies:
  - chart: ../charts/charts/common-test
    version: 0.1.0
  hooks:
  - events: ["postsync"]
    command: "kubectl"
    args: ["-n", "gpu-operator", "patch", "clusterpolicy/cluster-policy", "--type", "merge", "-p", "{'spec': {'devicePlugin': {'config': {'name': 'time-slicing-config', 'default': 'any'}}}}"]
- name: traefik
  chart: traefik/traefik
  version: 23.1.0
  inherit:
  - template: production
  disableValidationOnInstall: true
  dependencies:
  - chart: ../charts/charts/common-test
    version: 0.1.0
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  version: 1.4.2
  inherit:
  - template: production
  dependencies:
  - chart: ../charts/charts/common-test
    version: 0.1.0

helmfiles:
- ../private/helmfile.yaml
