---
- name: download installer
  ansible.builtin.get_url:
    dest: /tmp/pihole.sh
    url: https://install.pi-hole.net
    mode: '0755'
- name: create /etc/pihole
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
- name: template setupVars.conf
  ansible.builtin.template:
    dest: /etc/pihole/setupVars.conf
    src: templates/setupVars.conf.j2
- name: install packages
  ansible.builtin.apt:
    name: lighttpd-mod-openssl, sqlite3
    state: present
- name: install pihole
  ignore_errors: true
  ansible.builtin.command: /tmp/pihole.sh --unattended
