---
- name: download installer
  ansible.builtin.get_url:
    dest: /tmp/pihole.sh
    url: https://install.pi-hole.net
    mode: '0755'
- name: create /etc/pihole
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
- name: template setupVars.conf
  ansible.builtin.template:
    dest: /etc/pihole/setupVars.conf
    src: templates/setupVars.conf.j2
- name: install packages
  ansible.builtin.apt:
    name: lighttpd-mod-openssl, sqlite3
    state: present
- name: install pihole
  ignore_errors: true
  ansible.builtin.command: /tmp/pihole.sh --unattended
- name: Creating 05-custom.conf under dnsmasq.d
  ansible.builtin.copy:
    dest: /etc/dnsmasq.d/05-custom.conf 
    content: |
      server=/angrydonkey.io/10.5.5.3

      rev-server=10.5.5.1/24,192.168.55.1
