---
- name: copy ca public key
  ansible.builtin.copy:
    src: "{{ vault_ca_path }}"
    dest: /etc/ssh/trusted-user-ca-keys.pem
    mode: 0600
- name: update sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "EOF"
    regex: "TrustedUserCAKeys.*"
    line: "TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem"
  register: updated_sshd_config
- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: updated_sshd_config.changed
