---
- name: Read cloudflare token
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    engine_mount_point: homelab
    path: certbot
  delegate_to: localhost
  register: vault_certbot
- block:
    - name: Install python3 and pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
    - name: Install certbot and cloudflare
      ansible.builtin.pip:
        name:
          - certbot
          - certbot-dns-cloudflare
        state: present
        virtualenv: ~/certbot
        virtualenv_command: python3 -m venv
    - name: Create ~/.secrets/certbot
      ansible.builtin.file:
        path: ~/.secrets/certbot
        state: directory
    - name: Write credentials
      ansible.builtin.template:
        dest: ~/.secrets/certbot/cloudflare.ini
        src: templates/cloudflare.ini.j2
    - name: Check if cert has be installed
      become: true
      ansible.builtin.stat:
        path: /etc/letsencrypt/live/angrydonkey.io
      register: st
    - name: Request certificate
      shell: ". ~/certbot/bin/activate; certbot certonly --dns-cloudflare --dns-cloudflare-credentials ~/.secrets/certbot/cloudflare.ini -d '*.angrydonkey.io' --non-interactive --agree-tos -m {{ vault_certbot.data.data.cf_email }}"
      when: not st.stat.exists
    - name: Set permissions
      ansible.builtin.file:
        path: /etc/letsencrypt/live
        owner: www-data
        recurse: true
    - name: Setup cron for automatic renew
      ansible.builtin.cron:
        name: "certbot renew"
        minute: "0"
        hour: "0,12"
        job: "certbot renew --post-hook 'source ~/certbot-post-hook.sh'"
  become: true
