env:
  TZ: America/Los_Angeles

ingress:
  enabled: true
  hosts:
  - name: default
    host: homebox.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 1Gi

addons:
  rclone:
    persistence:
      config:
        enabled: true
