env:
  TZ: America/Los_Angeles
  PHOTOPRISM_ADMIN_PASSWORD: ref+vault://homelab/k8s/photoprism/#password
  PHOTOPRISM_ORIGINALS_PATH: /media/images
  PHOTOPRISM_IMPORT_PATH: /media/import

ingress:
  enabled: true
  hosts:
    - name: default
      host: photoprism.angrydonkey.io

persistence:
  config:
    enabled: true
    type: nfs
    server: 192.168.55.20
    path: /mnt/user/appdata/photoprism

  media:
    enabled: true
    type: nfs
    server: 192.168.55.20
    path: /mnt/user/media
