{{- define "common.pvc" }}
{{- $type := default "pvc" .Values.type }}
{{- if and (eq $type "pvc") .Values.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" (include "common.name" .) .name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $commonLabels := include "common.labels" . | fromYaml }}
  {{- $labels := mustMerge $commonLabels (default dict .Values.labels) }}
  labels:
  {{- toYaml $labels | nindent 4 }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ default "8Gi" .Values.size }}
  {{- with .Values.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
