- name: Check for service
  service_facts:
- name: Download, install and start Omada
  when: "'tpeap' not in services"
  block:
  - name: Install packages
    apt:
      name:
        - mongodb
        - jsvc
        - curl
        - openjdk-8-jre-headless
  - name: Ensure openjdk-11 not installed
    apt:
      name: openjdk-11-jre-headless
      state: absent
  - name: Create directory
    file:
      dest: /omada
      state: directory
  - name: Download installer
    get_url:
      url: https://static.tp-link.com/upload/software/2022/202208/20220822/Omada_SDN_Controller_v5.5.6_Linux_x64.tar.gz
      dest: /omada/Omada_SDN_Controller_v5.5.6_Linux_x64.tar.gz 
  - name: Unarchive installer
    unarchive:
      remote_src: true
      dest: /omada
      src: /omada/Omada_SDN_Controller_v5.5.6_Linux_x64.tar.gz
      extra_opts:
        --strip-components=1
  - name: Install Omada
    command: ./install.sh -y -n
    args:
      chdir: /omada
  - name: Reboot
    reboot:
  - name: Start service
    service:
      name: tpeap
      state: started
      enabled: true
