- name: Install packages
  ansible.builtin.apt:
    name:
      - mongodb
      - jsvc
      - curl
      - openjdk-8-jre-headless
- name: Download installer
  ansible.builtin.get_url:
    dest: /root/Omada_SDN_Controller_v5.7.4_Linux_x64.deb 
    url: https://static.tp-link.com/upload/software/2022/202211/20221121/Omada_SDN_Controller_v5.7.4_Linux_x64.deb
- name: Install Omada SDN Controller
  ansible.builtin.apt:
    deb: /root/Omada_SDN_Controller_v5.7.4_Linux_x64.deb
    state: present
- name: Transform certificate format
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/omada 
    content: |
      rm /opt/tplink/EAPController/data/keystore/eap.cer 
      rm /opt/tplink/EAPController/data/keystore/eap.keystore

      cp /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/cert.pem /opt/tplink/EAPController/data/keystore/eap.cer

      openssl pkcs12 -export \
      -in /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/cert.pem \
      -inkey /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/privkey.pem \
      -out /root/{{ ansible_facts['hostname'] }}.angrydonkey.io.p12 \
      -certfile /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/chain.pem \
      -password pass:tplink \
      -name eap

      keytool -importkeystore \
      -destkeystore /opt/tplink/EAPController/data/keystore/eap.keystore \
      -deststorepass tplink \
      -srckeystore /root/{{ ansible_facts['hostname'] }}.angrydonkey.io.p12 \
      -srcstoretype PKCS12 \
      -srcstorepass tplink
    mode: '0744'
  register: omada_hook
- name: Execute deploy hook
  ansible.builtin.shell: /etc/letsencrypt/renewal-hooks/deploy/omada 
  when: omada_hook['changed']
- name: Restart tpeap service
  ansible.builtin.shell: |
    tpeap stop 
    tpeap start
