---
- name: Updates all packages
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
- name: Install new packages
  become: true
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: present
  when: pkgs is defined
- name: Check if reboot required
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
- name: Reboot if required
  become: true
  throttle: 1
  reboot:
  when: reboot_required_file.stat.exists
