env:
  TZ: America/Los_Angeles

dnsConfig:
  options:
    - name: ndots
      value: "1"

ingress:
  enabled: true
  hosts:
  - name: default
    host: node-red.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 1Gi

initContainers:
  chown:
    image:
      repository: busybox
      tag: latest

    command: ['chown', '-R', '1000:1000', '/config']

    persistence:
      config:
        enabled: true

addons:
  rclone:
    persistence:
      config:
        enabled: true
