env:
  TZ: America/Los_Angeles

ingress:
  enabled: true

  hosts:
  - name: default
    host: kavita.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 8Gi

  media:
    enabled: true
    type: nfs
    server: 192.168.55.20
    path: /mnt/user/media
