{{- range .Values.ingressRoutes }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ printf "%s-%s" (include "common.name" $) .serviceName }}
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
  {{- $entryPoints := default (list "websecure") .entryPoints }}
  {{ toYaml $entryPoints | nindent 4 }}
  routes:
  - kind: Rule
    match: {{ default "Host(`{{ .host }}`)" .match }}
    services:
    - kind: Service
      name: {{ .serviceName }}
      namespace: {{ default $.Release.Namespace .namespace }}
      port: {{ .port }}
{{- end }}
