image:
  repository: lissy93/dashy

env:
  TZ: America/Los_Angeles

services:
  http:
    port: 80

ingress:
  http:
    enabled: false

persistence:
  app:
    enabled: false
    mountPath: /app/public
