---
- name: Check if vm exists
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    name: "{{ inventory_hostname }}"
    state: current
    vmid: "{{ vmid }}"
  ignore_errors: true
  delegate_to: localhost
  register: check_vm
- include_tasks: create-vm.yaml
  when: (check_vm.exception is undefined) and check_vm.failed
