nodeSelector:
  kubernetes.io/hostname: galaxy-03

dnsConfig:
  options:
    - name: ndots
      value: "1"

hostNetwork: true

securityContext:
  privileged: true

env:
  TZ: America/Los_Angeles

service:
  loadBalancerIP: "192.168.55.163"
  type: LoadBalancer

persistence:
  config:
    enabled: true
    type: pvc
    size: 1Gi

  zigbee:
    enabled: true
    type: hostpath
    path: /dev/ttyACM0
    mountType: "CharDevice"
    mountPath: /dev/zigbee

addons:
  rclone:
    persistence:
      config:
        enabled: true
