nodeSelector:
  kubernetes.io/hostname: galaxy-03

dnsConfig:
  options:
    - name: ndots
      value: "1"

hostNetwork: true

env:
  TZ: America/Los_Angeles

ingress:
  enabled: true
  hosts:
    - name: default
      host: ha.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 1Gi

  zigbee:
    enabled: true
    type: hostpath
    path: /dev/ttyACM0
    mountType: "CharDevice"
    mountPath: /dev/zigbee

addons:
  rclone:
    persistence:
      config:
        enabled: true
