addons:
  rclone:
    enabled: true

    image:
      tag: 0.1.3

    cronSchedule: "30 1 * * *"
    cronArgs: "-d 8 -f"

    globalArgs: "--password-file /root/.config/rclone/restic.txt"

    backupArgs: "--host {{ .Release.Name }}"

    restoreArgs: "--host {{ .Release.Name }}"

    destination: rclone:minio:apps

    restic:
      enabled: true

    persistence:
      rclone:
        enabled: true
        type: nfs
        server: 192.168.55.20
        path: /mnt/user/appdata/rclone
        mountPath: /root/.config/rclone
