# initContainers:
#   restore:
#     image:
#       repository: ghcr.io/jasonb5/rclone
#       tag: 0.1.2
# 
#     env:
#       RESTORE: true
#       BACKUP_APP: restic
#       RESTIC_PATH: /config
#       RESTIC_REPO: rclone:minio:apps
#       RESTIC_GLOBAL_FLAGS: "--password-file /root/.config/rclone/restic.txt"
#       RESTIC_FLAGS: "--host {{ .Release.Name }}"
# 
#     persistence:
#       rclone:
#         enabled: true
#         type: nfs
#         server: 192.168.55.20
#         path: /mnt/user/appdata/rclone
#         mountPath: /root/.config/rclone

addons:
  rclone:
    enabled: true

    cronSchedule: "30 1 * * *"

    globalFlags: "--password-file /root/.config/rclone/restic.txt"

    flags: "--host {{ .Release.Name }}"

    restic:
      enabled: true

      repo: rclone:minio:apps

    persistence:
      rclone:
        enabled: true
        type: nfs
        server: 192.168.55.20
        path: /mnt/user/appdata/rclone
        mountPath: /root/.config/rclone
