- name: Install and configure unbound 
  block:
  - name: Install unbound
    ansible.builtin.apt:
      name: unbound
      state: present
      update_cache: true
  - name: Copy configuration
    ansible.builtin.copy:
      dest: /etc/unbound/unbound.conf.d/pi-hole.conf
      src: files/pi-hole.conf
  - name: Restart unbound service
    ansible.builtin.systemd:
      name: unbound
      state: restarted
      enabled: true
  when: unbound is defined and unbound
- name: Download pihole installer
  ansible.builtin.get_url:
    mode: '0744'
    dest: /root/pihole-installer.sh
    url: https://install.pi-hole.net
- name: Create /etc/pihole
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
- name: Create setupVars.conf
  vars:
    pihole: "{{ lookup('community.hashi_vault.vault_kv2_get', 'pihole', engine_mount_point='homelab').data.data }}"
  ansible.builtin.copy:
    dest: /etc/pihole/setupVars.conf
    content: |
      WEBPASSWORD={{ pihole.password | hash('sha256') | hash('sha256') }}
      {% if unbound is defined and unbound %}
      PIHOLE_DNS_1=127.0.0.1#5335
      {% elif upstream_dns is defined %}
      PIHOLE_DNS_1={{ upstream_dns }}
      {% endif %}
      INSTALL_WEB=true
- name: Stop/disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
- name: Remove /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
- name: Create new /etc/resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver {{ upstream_dns }}
      search angrydonkey.io
- name: Install pi-hole
  ansible.builtin.shell: >
    /root/pihole-installer.sh
    --unattended
- name: Create certbot deploy hook
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/lighttpd
    content: |
      cat \
      /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/privkey.pem \
      /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/cert.pem | \
      tee /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/combined.pem

      systemctl restart lighttpd
    mode: '0744'
  register: deploy_hook
- name: Execute deploy script first time
  ansible.builtin.shell: /etc/letsencrypt/renewal-hooks/deploy/lighttpd
  when: deploy_hook['changed']
- name: Add lighttpd ssl
  ansible.builtin.copy:
    dest: /etc/lighttpd/external.conf
    content: |
      $HTTP["host"] == "{{ ansible_facts['hostname'] }}.angrydonkey.io" {
        setenv.add-environment = ("fqdn" => "true")

        $SERVER["socket"] == ":443" {
          ssl.engine = "enable"
          ssl.pemfile = "/etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/combined.pem"
          ssl.ca-file = "/etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/fullchain.pem"
          ssl.honor-cipher-order = "enable"
          ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
          ssl.use-sslv2 = "disable"
          ssl.use-sslv3 = "disable"
        }

        $HTTP["scheme"] == "http" {
          $HTTP["host"] =~ ".*" {
            url.redirect = (".*" => "https://%0$0")
          }
        }
      }
  register: lighttpd_ssl
- name: Restart lighttpd service
  ansible.builtin.systemd:
    name: lighttpd
    state: restarted
  when: lighttpd_ssl['changed']
- name: Copy ssh keys
  become: false
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') + '/.ssh/' + item }}"
    dest: "${HOME}/.ssh/{{ item }}"
    mode: '0600'
  loop:
    - id_homelab
    - id_homelab.pub
- name: Register ssh key
  become: false
  ansible.builtin.copy:
    dest: "~/.ssh/config"
    content: |
      IdentityFile ~/.ssh/id_homelab
- name: Authorize ssh key
  become: false
  ansible.posix.authorized_key:
    user: titters
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_homelab.pub') }}"
- name: Create gravity-sync directory
  ansible.builtin.file:
    path: /etc/gravity-sync
    state: directory
- name: Create gravity-sync config
  # only works when there are two servers
  ansible.builtin.copy:
    dest: /etc/gravity-sync/gravity-sync.conf 
    content: |
      {% set group = group_names | first -%}
      {% for peer in groups[group] %}
      {% if peer != inventory_hostname %}
      REMOTE_HOST='{{ hostvars[peer]['ansible_default_ipv4']['address'] }}'
      {% endif %}
      {% endfor %}
      REMOTE_USER='titters'
- name: Download install script
  ansible.builtin.get_url:
    dest: /root/gs-install.sh
    url: https://raw.githubusercontent.com/vmstan/gs-install/main/gs-install.sh
    mode: '0755'
- name: Install gravity-sync 
  ansible.builtin.shell: /root/gs-install.sh
- name: Automate gravity-sync
  ansible.builtin.shell: gravity-sync auto quad
  when: inventory_hostname == master
