- name: Install unbound
  apt:
    name: unbound
    state: present
- name: Copy pi-hole.conf
  copy:
    src: files/pi-hole.conf
    dest: /etc/unbound/unbound.conf.d
- name: Restart unbound
  systemd:
    name: unbound
    state: restarted
    enabled: true
- name: mkdir /etc/pihole
  file:
    path: /etc/pihole
    state: directory
- name: Check if setupVars.conf exists
  stat:
    path: /etc/pihole/setupVars.conf
  register: check_setupvars
- name: Create setupVars.conf
  vars:
    pihole: "{{ lookup('community.hashi_vault.vault_kv2_get', 'pihole', engine_mount_point='homelab').data.data }}"
  copy:
    dest: /etc/pihole/setupVars.conf
    content: |
      WEBPASSWORD={{ pihole.password|hash('sha256')|hash('sha256') }}
      PIHOLE_DNS_1=8.8.8.8
      PIHOLE_DNS_2=8.8.4.4
      INSTALL_WEB=true
  when: not check_setupvars.stat.exists
- name: Check if installer exists
  stat:
    path: /tmp/pihole.sh
  register: check_installer
- name: Download pi-hole installer
  get_url:
    dest: /tmp/pihole.sh
    url: https://install.pi-hole.net
    mode: 0755
  when: not check_installer.stat.exists
- name: Install pi-hole
  environment:
    PIHOLE_SKIP_OS_CHECK: true
  shell: /tmp/pihole.sh --unattended
  ignore_errors: true
  timeout: 30
- name: Replace PIHOLE_DNS_1
  replace:
    path: /etc/pihole/setupVars.conf
    regexp: '(.*PIHOLE_DNS_1)=.*'
    replace: '\1=127.0.0.1#5335'
- name: Replace PIHOLE_DNS_2
  replace:
    path: /etc/pihole/setupVars.conf
    regexp: '(.*PIHOLE_DNS_2)=.*'
    replace: '\1='
- name: Restart pihole dns
  shell: pihole restartdns
- name: Create combined.pem
  shell: >
    cat
    /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/privkey.pem
    /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/cert.pem
    | tee /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/combined.pem
- name: Chown live directory
  file:
    recurse: true
    path: /etc/letsencrypt/live
    owner: www-data
- name: Create external.conf
  copy:
    dest: /etc/lighttpd/external.conf
    content: |
      $HTTP["host"] == "{{ ansible_facts['hostname'] }}.angrydonkey.io" {
        setenv.add-evnironment = ("fqdn" => "true")

        $SERVER["socket"] == ":443" {
          ssl.engine = "enable"
          ssl.pemfile = "/etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/combined.pem"
          ssl.ca-file = "/etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/fullchain.pem"
        }

        $HTTP["scheme"] == "http" {
          $HTTP["host"] =~ ".*" {
            url.redirect = (".*" => "https://%0$0")
          }
        }
      }
- name: Restart lighttpd
  systemd:
    name: lighttpd
    state: restarted
