---
- name: download installer
  ansible.builtin.get_url:
    dest: /tmp/pihole.sh
    url: https://install.pi-hole.net
    mode: '0755'
- name: get admin password
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    path: pihole
    engine_mount_point: homelab
  delegate_to: localhost
  register: vault_pihole
- name: create /etc/pihole
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
- name: template setupVars.conf
  ansible.builtin.template:
    dest: /etc/pihole/setupVars.conf
    src: templates/setupVars.conf.j2
- name: install packages
  ansible.builtin.apt:
    name: lighttpd-mod-openssl, sqlite3
    state: present
- name: install pihole
  ansible.builtin.command: /tmp/pihole.sh --unattended
- name: copy external.conf
  ansible.builtin.copy:
    dest: /etc/lighttpd/conf-enabled/20-pihole-external.conf
    src: files/external.conf
  register: lighttpd_external
- name: restart lighttpd service
  ansible.builtin.systemd_service:
    name: lighttpd
    state: restarted
  when: lighttpd_external.changed
- name: register blocklists
  ansible.builtin.command: sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address, enabled, comment) VALUES ('{{ item.url }}', 1, '{{ item.comment }}')"
  ignore_errors: true
  loop: "{{ pihole_blocklist }}"
  register: blocklists
- name: reload pihole
  command: pihole restartdns reload-lists
  when: not blocklists.failed
