- name: Install unbound
  ansible.builtin.apt:
    name: unbound
    state: present
    update_cache: true
- name: Copy configuration
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    src: files/pi-hole.conf
- name: Restart unbound service
  ansible.builtin.systemd:
    name: unbound
    state: restarted
    enabled: true
- name: Download pihole installer
  ansible.builtin.get_url:
    mode: '0744'
    dest: /root/pihole-installer.sh
    url: https://install.pi-hole.net
- name: Create /etc/pihole
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
- name: Create setupVars.conf
  vars:
    pihole: "{{ lookup('community.hashi_vault.vault_kv2_get', 'pihole', engine_mount_point='homelab').data.data }}"
  ansible.builtin.copy:
    dest: /etc/pihole/setupVars.conf
    content: |
      WEBPASSWORD={{ pihole.password | hash('sha256') | hash('sha256') }}
      PIHOLE_DNS_1=127.0.0.1#5335
      INSTALL_WEB=true
- name: Stop/disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
- name: Remove /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
- name: Create new /etc/resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 10.50.20.1
      search angrydonkey.io
- name: Install pi-hole
  ansible.builtin.shell: >
    /root/pihole-installer.sh
    --unattended
- name: Create certbot deploy hook
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/lighttpd
    content: |
      cat \
      /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/privkey.pem \
      /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/cert.pem | \
      tee /etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/combined.pem

      systemctl restart lighttpd
    mode: '0744'
  register: deploy_hook
- name: Execute deploy script first time
  ansible.builtin.shell: /etc/letsencrypt/renewal-hooks/deploy/lighttpd
  when: deploy_hook['changed']
- name: Add lighttpd ssl
  ansible.builtin.copy:
    dest: /etc/lighttpd/external.conf
    content: |
      $HTTP["host"] == "{{ ansible_facts['hostname'] }}.angrydonkey.io" {
        setenv.add-environment = ("fqdn" => "true")

        $SERVER["socket"] == ":443" {
          ssl.engine = "enable"
          ssl.pemfile = "/etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/combined.pem"
          ssl.ca-file = "/etc/letsencrypt/live/{{ ansible_facts['hostname'] }}.angrydonkey.io/fullchain.pem"
          ssl.honor-cipher-order = "enable"
          ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
          ssl.use-sslv2 = "disable"
          ssl.use-sslv3 = "disable"
        }

        $HTTP["scheme"] == "http" {
          $HTTP["host"] =~ ".*" {
            url.redirect = (".*" => "https://%0$0")
          }
        }
      }
  register: lighttpd_ssl
- name: Restart lighttpd service
  ansible.builtin.systemd:
    name: lighttpd
    state: restarted
  when: lighttpd_ssl['changed']
