- name: Install packages
  ansible.builtin.apt:
    name: nfs-client
    state: present
- name: Download install script
  ansible.builtin.get_url:
    mode: '0744'
    dest: /root/k3s-installer.sh
    url: https://get.k3s.io
- block:
    - name: Install k3s server
      ansible.builtin.shell: >
        /root/k3s-installer.sh
        --disable traefik
        --disable local-storage
        --disable metrics-server
    - name: Read join token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_node_token
    - name: Copy k3s.yaml
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: true
    - name: Update k3s server address
      become: false
      delegate_to: localhost
      ansible.builtin.replace:
        path: "{{ lookup('env', 'HOME') }}/.kube/config"
        regexp: 127.0.0.1
        replace: "{{ ansible_facts['default_ipv4']['address'] }}"
  when: "'k3s_server' in group_names"
- block:
    - name: Get server hostvars
      ansible.builtin.set_fact:
        k3s_server_hostvars: "{{ hostvars[groups['k3s_server'] | first] }}"
    - name: Join node to cluster
      environment:
        K3S_URL: "https://{{ k3s_server_hostvars['ansible_facts']['default_ipv4']['address'] }}:6443"
        K3S_TOKEN: "{{ k3s_server_hostvars['k3s_node_token']['content'] | b64decode | trim }}"
      ansible.builtin.shell: /root/k3s-installer.sh
  when: "'k3s_agent' in group_names"
- import_tasks: nvidia.yaml
  when: "'k3s_gpu' in group_names"
