repositories:
- name: nvdp
  url: https://nvidia.github.io/k8s-device-plugin
- name: k8s-at-home
  url: https://k8s-at-home.com/charts/
- name: k8s-at-home-library
  url: https://library-charts.k8s-at-home.com

releases:
  - name: nvidia-device-plugin
    namespace: nvidia-device-plugin
    createNamespace: true
    chart: nvdp/nvidia-device-plugin
    version: 0.12.3
    values:
      - gfd:
          enabled: true
        runtimeClassName: nvidia
  - name: nvidia-device-plugin-post
    namespace: nvidia-device-plugin
    chart: charts/common
    version: 0.1.0
    values:
      - extraObjects:
          - apiVersion: node.k8s.io/v1
            kind: RuntimeClass
            metadata:
              name: nvidia
            handler: nvidia
    needs:
      - nvidia-device-plugin/nvidia-device-plugin
#   - name: jellyfin
#     namespace: default
#     chart: k8s-at-home/jellyfin
#     version: 9.5.3
#     values:
#       - values/common.yaml
#       - values/jellyfin.yaml
#   - name: vaultwarden
#     namespace: default
#     chart: k8s-at-home/vaultwarden
#     version: 5.3.2
#     values:
#       - env:
#           ADMIN_TOKEN: ref+vault://homelab/vaultwarden/#admin_token
#         persistence:
#           config:
#             enabled: true
#   - name: photoprism
#     namespace: default
#     chart: k8s-at-home/photoprism
#     version: 7.1.2
#     values:
#       - env:
#           TZ: America/Los_Angeles
#           PHOTOPRISM_PUBLIC: true
#   - name: minecraft-ntc2
#     namespace: default
#     chart: charts/minecraft
#     version: 0.1.0
#     values:
#       - env:
#           INSTALLER_PATH: /data/minecraft/Not+Too+Complicated2-1.5.1-server.zip
#         probes:
#           startup:
#             spec:
#               periodSeconds: 10
#         persistence:
#           modpack:
#             enabled: true
#             size: 16Gi
#             accessMode: ReadWriteOnce
#           data:
#             enabled: true
#             type: nfs
#             server: 192.168.55.53
#             path: /mnt/user/backup
#   - name: post
#     namespace: default
#     chart: charts/default_post
#     version: 0.1.0
#     values:
#       - ingressRoutes:
#           longhorn:
#             service: longhorn-frontend
#             namespace: longhorn-system
#             port: 80
#           jellyfin:
#             namespace: default
#             port: 8096
#           minecraft-ntc2:
#             type: tcp
#             namespace: default
#             port: 25565
#           vaultwarden:
#             namespace: default
#             port: 80
#           photoprism:
#             namespace: default
#             port: 2342

# these are processed before releases in this state file
# ensuring longhorn CRDs are available
helmfiles:
- path: prereqs.yaml
