repositories:
- name: homelab
  url: https://jasonb5.github.io/homelab/
- name: nvidia
  url: https://helm.ngc.nvidia.com/nvidia
- name: jupyterhub
  url: https://jupyterhub.github.io/helm-chart

releases:
  - name: jupyterhub
    namespace: default
    chart: jupyterhub/jupyterhub
    version: 2.0.0
    values:
      - values/jupyterhub.yaml
  - name: jupyterhub-extra
    namespace: default
    chart: ../charts/common-utils
    version: 0.1.0
    values:
      - values/jupyterhub-extra.yaml
    needs:
      - default/jupyterhub
  - name: nvidia-gpu-operator
    namespace: gpu-operator
    createNamespace: true
    chart: nvidia/gpu-operator
    version: v22.9.0
    disableValidationOnInstall: true
    values:
      - values/gpu-operator.yaml
    dependencies:
    - chart: ../charts/common-utils
      version: 0.1.0
  - name: jellyfin
    namespace: default
    chart: homelab/jellyfin
    version: 0.1.0
    values:
      - values/common.yaml
      - values/jellyfin.yaml
  - name: vaultwarden
    namespace: default
    chart: homelab/vaultwarden
    version: 0.1.0
    values:
      - values/common.yaml
      - values/vaultwarden.yaml
  - name: gotify
    namespace: default
    chart: ../charts/gotify
    version: 0.1.0
    values:
      - values/common.yaml
      - values/gotify.yaml

# these are processed before releases in this state file
# ensuring longhorn CRDs are available
helmfiles:
- path: prereqs.yaml
