repositories:
- name: homelab
  url: https://jasonb5.github.io/homelab/

releases:
  - name: nvidia-gpu-operator
    namespace: gpu-operator
    createNamespace: true
    values:
  - name: jellyfin
    namespace: default
    chart: homelab/jellyfin
    version: 0.1.0
    values:
      - values/common.yaml
      - values/jellyfin.yaml
  - name: vaultwarden
    namespace: default
    chart: homelab/vaultwarden
    version: 0.1.0
    values:
      - values/common.yaml
      - values/vaultwarden.yaml

# these are processed before releases in this state file
# ensuring longhorn CRDs are available
helmfiles:
- path: prereqs.yaml
