repositories:
- name: longhorn
  url: https://charts.longhorn.io

releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.3.1
    values:
      - persistence:
          defaultClassReplicaCount: 2
    wait: true
