repositories:
- name: longhorn
  url: https://charts.longhorn.io
- name: traefik
  url: https://helm.traefik.io/traefik

releases:
  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    version: 1.3.2
    values:
      - persistence:
          defaultClassReplicaCount: 2
      - common-utils:
          type: null
          secrets:
            longhorn-s3:
              AWS_ACCESS_KEY_ID: Vz4Hez0ECCX0wflZ
              AWS_SECRET_ACCESS_KEY: tH2vyynlHOKseieGEWiwl0b8o0FghnK3
              AWS_ENDPOINTS: https://minio.angrydonkey.io
    dependencies:
      - chart: ../charts/common-utils
        version: 0.1.0
    wait: true
  - name: traefik
    namespace: default
    chart: traefik/traefik
    version: 18.0.0
    values:
      - values/traefik.yaml
    disableValidationOnInstall: true
    dependencies:
      - chart: ../charts/common-utils
        version: 0.1.0
    needs:
    - longhorn-system/longhorn
