repositories:
- name: longhorn
  url: https://charts.longhorn.io
- name: traefik
  url: https://helm.traefik.io/traefik
- name: homelab
  url: https://jasonb5.github.io/homelab/

releases:
  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    version: 1.3.2
    values:
      - persistence:
          defaultClassReplicaCount: 2
    wait: true
  - name: traefik
    namespace: default
    chart: traefik/traefik
    version: 18.0.0
    values:
      - values/traefik.yaml
      - utils:
          ingressRoutes:
            - host: longhorn.angrydonkey.io
              namespace: longhorn-system
              serviceName: longhorn-frontend
              port: 80
    dependencies:
      - chart: homelab/utils
        version: 0.1.1
    needs:
    - longhorn-system/longhorn
