repositories:
- name: traefik
  url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: default
    chart: traefik/traefik
    version: 14.0.1
    values:
      - values/traefik.yaml
    wait: true
