securityContext:
  privileged: true

env:
  TZ: America/Los_Angeles

nodeSelector:
  kubernetes.io/hostname: galaxy-03

ingress:
  enabled: true
  hosts:
  - name: default
    host: zwave-js-ui.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 2Gi

  zwave:
    enabled: true
    type: hostpath
    path: /dev/ttyUSB0
    mountType: "CharDevice"
    mountPath: /dev/zwave

addons:
  rclone:
    persistence:
      config:
        enabled: true
