env:
  TZ: America/Los_Angeles

ingress:
  enabled: true
  hosts:
  - name: default
    host: zwave-js-ui.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 8Gi

  zwave:
    enabled: true
    type: hostpath
    path: /dev/ttyUSB0
    mountType: "CharDevice"
    mountPath: /dev/zwave
