persistence:
  public:
    enabled: true

extraObjects:
  - apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: dashy
      namespace: default
    spec:
      entryPoints:
        - websecure
      routes:
      - kind: Rule
        match: Host(`dashy.angrydonkey.io`)
        services:
        - kind: Service
          name: dashy-http
          namespace: default
          port: 80
