hostNetwork: true

persistence:
  config:
    enabled: true
    size: 32G

  media:
    enabled: true
    type: nfs
    server: 10.50.20.181
    path: /mnt/user/media

extraObjects:
  - |
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: {{ include "common.name" . }}
      namespace: {{ .Release.Namespace }}
    spec:
      entryPoints:
        - websecure
      routes:
      - kind: Rule
        match: Host(`jellyfin.angrydonkey.io`)
        services:
        - kind: Service
          name: jellyfin-http
          namespace: default
          port: 8096
