deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.35
      command: ["sh", "-c", "touch /data/acme.json && chmod -Rv 600 /data/* && chown 65532:65532 /data/acme.json"]
      volumeMounts:
        - name: data
          mountPath: /data

logs:
  general:
    level: INFO

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: traefik-cloudflare
        key: token

ports:
  traefik:
    expose: true
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
      certResolver: letsencrypt
      domains:
      - main: "*.angrydonkey.io"

persistence:
  enabled: true

certResolvers:
  letsencrypt:
    email: ref+vault://homelab/cloudflare/#email
    dnsChallenge:
      provider: cloudflare
    storage: /data/acme.json

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-cloudflare
      namespace: default
    stringData:
      token: ref+vault://homelab/cloudflare/#token
    type: Opaque
