persistence:
  data:
    enabled: true

env:
  SIGNUPS_ALLOWED: "false"
  ADMIN_TOKEN: ref+vault://homelab/vaultwarden/#admin_token 

extraObjects:
  - |
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: {{ include "common.name" . }}
      namespace: {{ .Release.Namespace }}
    spec:
      entryPoints:
        - websecure
      routes:
      - kind: Rule
        match: Host(`vaultwarden.angrydonkey.io`)
        services:
        - kind: Service
          name: vaultwarden-http
          namespace: default
          port: 80
