secret:
  default:
    GOTIFY_DEFAULTUSER_PASS: ref+vault://homelab/k8s/gotify#password

envFrom:
  default: secret

securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE

ingress:
  default:
    enabled: true
    host: gotify.angrydonkey.io

persistence:
  config:
    enabled: true
    size: 1Gi
