env:
  TZ: America/Los_Angeles
  GOTIFY_DEFAULTUSER_PASS: ref+vault://homelab/k8s/gotify#password

dnsConfig:
  options:
    - name: ndots
      value: "1"

securityContext:
  fsGroup: 0

ingress:
  enabled: true
  hosts:
    - name: default
      host: gotify.angrydonkey.io

persistence:
  config:
    enabled: true
    type: pvc
    size: 1Gi
    mountPath: /app/data

addons:
  rclone:
    persistence:
      config:
        enabled: true
