env:
  TZ: America/Los_Angeles
  GOTIFY_DEFAULTUSER_PASS: ref+vault://homelab/k8s/gotify#password

ingress:
  enabled: true
  hosts:
    - name: default
      host: gotify.angrydonkey.io

persistence:
  data:
    enabled: true
    type: pvc
    size: 8Gi

addons:
  rclone:
    env:
      CRON: '* 4 * * *'
      SOURCE: /data
      DESTINATION: minio:apps/gotify
      FLAGS: '--create-empty-src-dirs'

    persistence:
      data:
        enabled: true
