secret:
  default:
    GOTIFY_DEFAULTUSER_PASS: ref+vault://homelab/k8s/gotify#password

env:
  GOTIFY_DEFAULTUSER_NAME: "titters"

envFrom:
  default: secret

service:
  default:
    enabled: true

ingress:
  default:
    enabled: true
    host: gotify.angrydonkey.io
