nodeSelector:
  area: rack

resources:

service:
  default:
    enabled: true

ingress:
  default:
    enabled: true
    host: jellyfin.angrydonkey.io

persistence:
  config:
    enabled: true
    size: 16Gi

  data:
    enabled: true
    type: nfs
    server: 192.168.55.20
    path: /mnt/user/media
