loki:
  persistence:
    size: 4Gi

grafana:
  enabled: true

  adminUser: titters
  adminPassword: ref+vault://homelab/k8s/grafana#password

  persistence:
    enabled: true

  ingress:
    enabled: true

    hosts:
    - grafana.angrydonkey.io
