- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present
- name: Add docker apt key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg 
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu focal stable"
    state: present
- name: Update cache
  apt:
    update_cache: true
- name: Install docker
  apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - python3-docker
    state: present
- name: Portainer volume
  community.docker.docker_volume:
    name: portainer_data
- name: Install portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9443:9443"
    mounts:
      - source: portainer_data
        target: /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
