---
- name: Check for VM template
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    name: "{{ hostname }}"
    state: current
    vmid: "{{ vmid }}"
  delegate_to: localhost
  ignore_errors: true
  register: checkvm
- name: Create VM
  throttle: 1
  community.general.proxmox_kvm:
    agent: true
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    bios: ovmf
    boot: d
    bootdisk: virtio0
    cicustom: "user=local:snippets/{{ vmid }}-user.yaml,network=local:snippets/{{ vmid }}-network.yaml"
    citype: nocloud
    cores: "{{ cores }}"
    cpu: host
    description: "{{ description | default('') }}"
    efidisk0:
      efitype: 4m
      format: raw
      pre_enrolled_keys: false
      storage: local-lvm
    ide:
      ide2: local-lvm:cloudinit,format=raw
    machine: q35
    memory: "{{ memory }}"
    name: "{{ hostname }}"
    net:
      net0: "virtio={{ mac_address }},bridge=vmbr0,firewall=1"
    node: "{{ node }}"
    ostype: l26
    scsihw: virtio-scsi-pci
    serial:
      serial0: socket
    state: present
    update: "{{ checkvm is not failed }}"
    vga: serial0
    vmid: "{{ vmid }}"
  delegate_to: localhost
  register: vm
  until: vm is not failed
  retries: 10
  when: checkvm is failed
- name: Stop VM for update
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    force: true
    name: "{{ hostname }}"
    state: stopped
    vmid: "{{ vmid }}"
  delegate_to: localhost
  ignore_errors: true
- name: Update VM
  throttle: 1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    cicustom: "user=local:snippets/{{ inventory_hostname }}-{{ vmid }}-user.yaml,network=local:snippets/{{ inventory_hostname }}-{{ vmid }}-network.yaml"
    citype: nocloud
    cores: "{{ cores }}"
    memory: "{{ memory }}"
    net:
      net0: "model=virtio"
    node: "{{ node }}"
    state: present
    update: true
    vmid: "{{ vmid }}"
  delegate_to: localhost
  ignore_errors: true
- name: Attach cloudinit disk image
  community.general.proxmox_disk:
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    disk: virtio0
    import_from: "/mnt/pve/iso/{{ image }}"
    name: "{{ hostname }}"
    state: present
    storage: local-lvm
    vmid: "{{ vmid }}"
  delegate_to: localhost
- name: Resize disk image
  community.general.proxmox_disk:
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    disk: virtio0
    name: "{{ hostname }}"
    size: "{{ disk_size }}"
    state: resized
    vmid: "{{ vmid }}"
  delegate_to: localhost
- name: Start VM
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_password: "{{ proxmox_password }}"
    api_user: "{{ proxmox_user }}"
    name: "{{ hostname }}"
    state: started
    vmid: "{{ vmid }}"
  delegate_to: localhost
  ignore_errors: true
