---
- name: deploy Pi-hole
  hosts: pihole
  gather_facts: false
  vars:
    ansible_user: root
    vault_url: https://vault.angrydonkey.io
  roles:
    - certbot
    - pihole
  tags: pihole
- name: deploy omada software controller
  hosts: omada
  gather_facts: false
  vars:
    ansible_user: root
    vault_url: https://vault.angrydonkey.io
    cf_use_key: true
  roles:
    - certbot
    - omada
  tags:
    - omada
