- name: Create Vault CA and signing roles
  hosts: localhost
  gather_facts: false
  roles:
    - role: vault/client-key-signing

- name: Deploy Vault CA public key and update sshd_config
  hosts: baremetal
  gather_facts: true
  vars:
    ansible_user: root
  roles:
    - role: vault/deploy-ca

- name: Provision VMs on proxmox hosts
  hosts: vms
  gather_facts: false
  vars:
    ansible_user: titters
  roles:
    - role: proxmox

- name: Install apps to VMs
  hosts: vms
  gather_facts: false
  vars:
    ansible_user: titters
  roles:
    - role: apps/certbot
      when: certbot is defined and certbot
    - role: apps/main
