- hosts: pihole
  gather_facts: false
  roles:
    - role: pihole
      vars:
        pihole_install: true
  tags:
    - pihole
- hosts: omada
  gather_facts: false
  roles:
    - role: omada
  tags:
    - omada
