- name: Create Vault CA and signing roles
  hosts: localhost
  gather_facts: false
  roles:
    - role: vault/client-key-signing
  tags: [ vault, vault_bootstrap ]

- name: Deploy Vault CA public key and update sshd_config
  hosts: baremetal
  gather_facts: true
  vars:
    ansible_user: root
  roles:
    - role: vault/deploy-ca
  tags: [ vault ] 

- name: Provision VMs on proxmox hosts
  hosts: vms
  gather_facts: false
  roles:
    - role: proxmox
  tags: [ proxmox ]

- name: Install apps to VMs
  hosts: vms
  gather_facts: false
  vars:
    ansible_user: titters
  tasks:
    - include_role:
        name: vms
        apply:
          tags: [ vms ]
      tags: [ vms ]
    - include_role:
        name: apps/certbot
        apply:
          tags: [ certbot ]
      when: "'certbot' in group_names"
      tags: [ certbot ]
    - include_role:
        name: apps/pihole
        apply:
          tags: [ pihole ]
      when: "'pihole' in group_names"
      tags: [ pihole ]
    - include_role:
        name: apps/omada
        apply:
          tags: [ omada ]
      when: "'omada' in group_names"
      tags: [ omada ]
