all:
  children:
    k3s:
      children:
        k3s_server:
          hosts:
            k3s-node1.angrydonkey.io:
        k3s_agent:
          hosts:
            k3s-node2.angrydonkey.io:
        k3s_gpu:
          hosts:
            k3s-node1.angrydonkey.io:

    docker:
      hosts:
        europa.angrydonkey.io:

    omada:
      hosts:
        omada.angrydonkey.io:

    pihole:
      hosts:
        pihole.angrydonkey.io:
        europa.angrydonkey.io:
