all:
  children:
    proxmox:
      hosts:
        callisto:
          ansible_host: 192.168.55.150
        ceres:
          ansible_host: 192.168.55.151
    vms:
      hosts:
        charon:
          ansible_host: 192.168.55.20
        galaxy-01:
          ansible_host: 192.168.55.21
          ip: 192.168.55.21
          vmid: 5000
          description: "Kubernetes node"
          node: callisto
          cores: 4
          memory: 8192
          image: ubuntu-22.04-server-cloudimg-amd64.img
          mac_address: da:f3:ee:97:3c:e8
          disk_size: 96G
          node_labels:
            kubernetes.io/area: rack
        galaxy-02:
          ansible_host: 192.168.55.22
          ip: 192.168.55.22
          vmid: 5001
          description: "Kubernetes node"
          node: callisto
          cores: 4
          memory: 8192
          image: ubuntu-22.04-server-cloudimg-amd64.img
          mac_address: da:71:46:a3:17:39
          disk_size: 96G
          node_labels:
            kubernetes.io/area: rack
        galaxy-03:
          ansible_host: 192.168.55.23
          ip: 192.168.55.23
          vmid: 5000
          description: "Kubernetes node"
          node: ceres
          cores: 4
          memory: 8192
          image: ubuntu-22.04-server-cloudimg-amd64.img
          mac_address: da:f4:9b:e5:8b:bd
          disk_size: 96G
          node_labels:
            kubernetes.io/area: router
        lo-01:
          vmid: 5001
          description: "Primary Pi-hole"
          node: ceres
          cores: 2
          memory: 2048
          image: ubuntu-22.04-server-cloudimg-amd64.img
          mac_address: de:fe:a6:ad:c1:80
          disk_size: 8G
    pihole:
      hosts:
        lo-01:
    unraid:
      hosts:
        charon:
    kubespray:
      children:
        kube_control_plane:
          hosts:
            galaxy-01:
            galaxy-02:
            galaxy-03:
        kube_node:
          hosts:
            galaxy-01:
            galaxy-02:
            galaxy-03:
        etcd:
          hosts:
            galaxy-01:
            galaxy-02:
            galaxy-03:
        k8s_cluster:
          children:
            kube_control_plane:
            kube_node:
        calico_rr:
          hosts: {}
