all:
  children:
    vms:
      children:
        hosts:
          charon.angrydonkey.io:
    baremetal:
      hosts:
        callisto.angrydonkey.io:
        deimos.angrydonkey.io:
        ceres.angrydonkey.io:
      children:
        kubernetes:
          hosts:
            k8s-01.angrydonkey.io:
            k8s-02.angrydonkey.io:
            k8s-03.angrydonkey.io:
    pihole:
      hosts:
        pihole-01.angrydonkey.io:
    omada:
      hosts:
        omada.angrydonkey.io:
