all:
  children:
    k3s:
      children:
        k3s_server:
          hosts:
            k3s-node3.angrydonkey.io:
              vars:
                labels: location=router
        k3s_agent:
          hosts:
            k3s-node1.angrydonkey.io:
              vars:
                labels: location=rack
            k3s-node2.angrydonkey.io:
              vars:
                labels: location=rack
    pihole:
      vars:
        extra_domains:
          - pihole.angrydonkey.io
        unbound: true
        upstream_dns: 192.168.55.1
        master: pihole1.angrydonkey.io
        keepalived:
          vip: 192.168.55.240/24
      hosts:
        pihole1.angrydonkey.io:
        pihole2.angrydonkey.io:
    omada:
      hosts:
        omada.angrydonkey.io:
