---
- name: Apply k3s role
  become: true
  hosts: k3s
  roles:
    - role: k3s
      tags:
        - k3s
- name: Apply omada role
  hosts: omada
  become: true
  roles:
    - role: omada
      tags:
        - omada
- name: Apply pihole role
  hosts: pihole
  become: true
  roles:
    - role: certbot
      tags:
        - certbot
    - role: pihole
      tags:
        - pihole
