---
- name: Install k3s
  hosts: k3s
  become: true
  roles:
    - role: k3s
  tags: k3s
- name: Install pihole
  hosts: pihole
  become: true
  roles:
    - role: certbot
      tags: certbot-install
    - role: pihole
      tags: pihole-Install
  tags: pihole
- name: Install Omada SDN Controller
  hosts: omada 
  become: true
  roles:
    - role: certbot
      tags: certbot-install
    - role: omada
      tags: omada-install
  tags: omada
