all:
  hosts:
    k8s-01:
      ansible_host: 192.168.55.22
      ip: 192.168.55.22
      access_ip: 192.168.55.22
      node_labels:
        area: router
    k8s-02:
      ansible_host: 192.168.55.23
      ip: 192.168.55.23
      access_ip: 192.168.55.23
      node_labels:
        area: rack
    k8s-03:
      ansible_host: 192.168.55.24
      ip: 192.168.55.24
      access_ip: 192.168.55.24
      node_labels:
        area: rack
  children:
    kube_control_plane:
      hosts:
        k8s-01:
        k8s-02:
        k8s-03:
    kube_node:
      hosts:
        k8s-01:
        k8s-02:
        k8s-03:
    etcd:
      hosts:
        k8s-01:
        k8s-02:
        k8s-03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
