hub:
  config:
    Authenticator:
      admin_users:
        - titters

    ConfigurableHTTPProxy:
      auth_token: isfNZJmp9Q1Oo5TObyia3KmTPJK7JzrY8taDWlLCdOYClE58OQTgMTmIFwgGln9Y

    JupyterHub:
      cookie_secret: a7ef6a657296ec8cd8d9948e5caca170ccfe2f3d6d29cf466005597a754748a8

    CryptKeeper:
      keys:
      - 06zTUyce0RpNNfSwgOIkwFtd8CSu7Dvq3ZCED4BefAcTXiU9lIDPn8kQVs8Fq6oYCg==

singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest

  defaultUrl: /lab

  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"

  profileList:
    - display_name: "Minimal notebook"
      description: "Minimal notebook"
      default: true
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"

  cloudMetadata:
    blockWithIptables: false

  storage:
    capacity: 16Gi

    extraVolumes:
      - name: shm-volume
        emptyDir:
          medium: Memory
      - name: archive-volume
        nfs:
          server: 192.168.55.20
          path: /mnt/user/archive
      - name: backup-volume
        nfs:
          server: 192.168.55.20
          path: /mnt/user/backup
    extraVolumeMounts:
      - name: shm-volume
        mountPath: /dev/shm
      - name: archive-volume
        mountPath: /home/jovyan/archive
      - name: backup-volume
        mountPath: /home/jovyan/backup

  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        MappingKernelManager:
          cull_idle_timeout: 1200
          cull_interval: 120
          cull_connected: true
          cull_busy: false

  networkPolicy:
    enabled: false

ingress:
  enabled: true
  hosts:
    - jupyterhub.angrydonkey.io
  pathType: ImplementationSpecific

prePuller:
  hook:
    enabled: false

  continuous:
    enabled: false

cull:
  enabled: true
  users: true
  adminUsers: true

scheduling:
  userScheduler:
    enabled: false
