- name: Install certbot snap
  snap:
    classic: true
    name: certbot
    state: present
- name: Trust certbot plugin
  command: snap set certbot trust-plugin-with-root=ok
- name: Install certbot-dns-cloudflare plugin
  snap:
    classic: true
    name: certbot-dns-cloudflare
    state: present
- name: Create symlink
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
- name: Make /etc/certbot
  file:
    path: /etc/certbot
    state: directory
- name: Create cloudflare.ini
  copy:
    dest: /etc/certbot/cloudflare.ini
    content: |
      dns_cloudflare_api_token = {{ lookup('community.hashi_vault.vault_kv2_get', 'cloudflare', engine_mount_point='homelab').data.data.token }}
    mode: 0600
- name: Obtain certificate
  command: >
    certbot certonly 
    -n 
    -m "{{ lookup('community.hashi_vault.vault_kv2_get', 'cloudflare', engine_mount_point='homelab').data.data.email }}"
    --agree-tos
    --dns-cloudflare
    --dns-cloudflare-credentials /etc/certbot/cloudflare.ini
    -d pihole.angrydonkey.io
