persistence:
  defaultClass: false

defaultSettings:
  storageReservedPercentageForDefaultDisk: 15
  defaultReplicaCount: 3
  removeSnapshotsDuringFilesystemTrim: true

ingress:
  enabled: true
  host: longhorn.angrydonkey.io

commonlib:
  extraObjects:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: longhorn-hourly-snapshot
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: driver.longhorn.io
    allowVolumeExpansion:  true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
      recurringJobSelector: '[
        {
          "name": "hourly-snapshot",
          "isGroup": true
        }
      ]'
